### ISSUE TITLE
Add idiotickey to auths.json in vps

### ISSUE THREAD

**Issue by SharpBit** [cree-py/creepy.py#19]
@freetnt5852 also send it in #creators in the discord so i can have it locally

**Comment by SharpBit** [comment]
@freetnt5852 read the title

**Comment by ravener** [comment]
Lol

**Comment by SharpBit** [comment]
@freetnt5852 close the issue if u did it

**Comment by ravener** [comment]
O forgot

**Comment by ravener** [comment]
Lemme close it

**Comment by ravener** [comment]
Lol
